{self}: {
  config,
  lib,
  pkgs,
  ...
}: let
  inherit
    (lib)
    attrValues
    concatLines
    concatMapStringsSep
    escapeShellArg
    filterAttrs
    flatten
    literalExpression
    mapAttrs
    mapAttrsToList
    mkDefault
    mkEnableOption
    mkIf
    mkMerge
    mkOption
    nameValuePair
    optional
    types
    unique
    ;

  cfg = config.services.unvanquished;

  enabledServers = filterAttrs (_: server: server.enable) cfg.servers;
  enabledUsers = unique (mapAttrsToList (_: server: server.user) enabledServers);
  enabledGroups = unique (mapAttrsToList (_: server: server.group) enabledServers);

  renderServerConfig = name: server:
    concatLines (
      [
        "// Generated by the Unvanquished NixOS module."
        "set sv_hostname ${escapeShellArg server.hostname}"
      ]
      ++ optional (server.port != null) "set net_port ${toString server.port}"
      ++ optional (server.port6 != null) "set net_port6 ${toString server.port6}"
      ++ server.settings
      ++ optional (server.extraConfig != "") server.extraConfig
    );

  mkServerService = name: server: let
    configFile = pkgs.writeText "unvanquished-${name}-server.cfg" (renderServerConfig name server);
    stateDir = server.stateDir;
    screenBin = "${server.screenPackage}/bin/screen";
    sessionName = server.screenSessionName;
    startScript = pkgs.writeShellScript "unvanquished-${name}-start" ''
      cd ${escapeShellArg stateDir}
      exec ${screenBin} -U -DmS ${escapeShellArg sessionName} \
        ${escapeShellArg "${server.package}/bin/daemonded"} \
        -homepath ${escapeShellArg stateDir} \
        -libpath ${escapeShellArg "${server.package}/bin"} \
        ${concatMapStringsSep " \\\n        " (path: "-pakpath ${escapeShellArg path}") server.pakPaths} \
        ${concatMapStringsSep " \\\n        " escapeShellArg server.daemonArgs} \
        +exec server.cfg \
        ${concatMapStringsSep " \\\n        " escapeShellArg server.gameArgs}
    '';
    stopScript = pkgs.writeShellScript "unvanquished-${name}-stop" ''
      if ${screenBin} -S ${escapeShellArg sessionName} -Q select . >/dev/null 2>&1; then
        exec ${screenBin} -S ${escapeShellArg sessionName} -p 0 -X stuff $'quit\r'
      fi

      exit 0
    '';
    cleanupScript = pkgs.writeShellScript "unvanquished-${name}-cleanup" ''
      ${screenBin} -S ${escapeShellArg sessionName} -X quit >/dev/null 2>&1 || true
    '';
  in {
    description = "Unvanquished dedicated server (${name})";
    wantedBy = ["multi-user.target"];
    after = ["network.target"];
    wants = ["network.target"];

    preStart = ''
      install -d -m 0750 -o ${server.user} -g ${server.group} ${escapeShellArg stateDir}
      install -d -m 0750 -o ${server.user} -g ${server.group} ${escapeShellArg "${stateDir}/config"}
      install -d -m 0750 -o ${server.user} -g ${server.group} ${escapeShellArg "${stateDir}/pkg"}
      install -m 0640 -o ${server.user} -g ${server.group} ${configFile} ${escapeShellArg "${stateDir}/config/server.cfg"}

      if ${screenBin} -S ${escapeShellArg sessionName} -Q select . >/dev/null 2>&1; then
        ${screenBin} -S ${escapeShellArg sessionName} -X quit
        sleep 1
      fi
    '';

    serviceConfig = {
      Type = "simple";
      User = server.user;
      Group = server.group;
      WorkingDirectory = "/";
      Restart = "always";
      RestartSec = 5;
      TimeoutStopSec = 15;
      ExecStart = startScript;
      ExecStop = stopScript;
      ExecStopPost = cleanupScript;
    };
  };
in {
  options.services.unvanquished = {
    servers = mkOption {
      default = {};
      description = "Dedicated Unvanquished server instances.";
      type = types.attrsOf (types.submodule ({name, ...}: {
        options = {
          enable = mkEnableOption "this Unvanquished server instance";

          package = mkOption {
            type = types.package;
            default = self.packages.${pkgs.system}.server;
            defaultText = literalExpression "self.packages.\${pkgs.system}.server";
            description = "Unvanquished server package to run.";
          };

          screenPackage = mkOption {
            type = types.package;
            default = pkgs.screen;
            defaultText = literalExpression "pkgs.screen";
            description = "GNU Screen package used to host the interactive server console.";
          };

          screenSessionName = mkOption {
            type = types.str;
            default = "unvanquished-${name}";
            description = "Name of the detached Screen session for this instance.";
          };

          user = mkOption {
            type = types.str;
            default = "unvanquished";
            description = "System user used to run this server.";
          };

          group = mkOption {
            type = types.str;
            default = "unvanquished";
            description = "System group used to run this server.";
          };

          stateDir = mkOption {
            type = types.str;
            default = "/var/lib/unvanquished/${name}";
            description = "Persistent homepath for this server instance.";
          };

          pakPaths = mkOption {
            type = types.listOf types.str;
            default = [];
            example = ["/srv/unvanquished/pkg"];
            description = "Pak search paths passed with repeated `-pakpath` arguments.";
          };

          hostname = mkOption {
            type = types.str;
            default = name;
            description = "Value written to `sv_hostname` in the generated `server.cfg`.";
          };

          port = mkOption {
            type = types.nullOr types.port;
            default = 27960;
            description = "IPv4 port written to `net_port` in the generated config.";
          };

          port6 = mkOption {
            type = types.nullOr types.port;
            default = null;
            description = "IPv6 port written to `net_port6` in the generated config.";
          };

          openFirewall = mkOption {
            type = types.bool;
            default = false;
            description = "Open the configured server ports in the firewall.";
          };

          daemonArgs = mkOption {
            type = types.listOf types.str;
            default = [];
            example = ["-set" "net_enabled" "3" "-set" "dedicated" "2"];
            description = "Extra engine arguments appended before game commands.";
          };

          gameArgs = mkOption {
            type = types.listOf types.str;
            default = [];
            example = ["+map" "plat23"];
            description = "Extra game commands appended after `+exec server.cfg`.";
          };

          settings = mkOption {
            type = types.listOf types.str;
            default = [];
            example = [
              "set dedicated 2"
              "set g_motd ${escapeShellArg "Welcome"}"
            ];
            description = "Additional lines appended to the generated `server.cfg`.";
          };

          extraConfig = mkOption {
            type = types.lines;
            default = "";
            description = "Raw text appended to the generated `server.cfg`.";
          };
        };
      }));
    };
  };

  config = mkMerge [
    (mkIf (enabledServers != {}) {
      systemd.services =
        lib.mapAttrs'
        (name: server: nameValuePair "unvanquished-server-${name}" (mkServerService name server))
        enabledServers;

      assertions =
        mapAttrsToList (name: server: {
          assertion = server.pakPaths != [];
          message = "services.unvanquished.servers.${name}.pakPaths must not be empty.";
        })
        enabledServers;
    })

    (mkIf (enabledServers != {}) {
      networking.firewall.allowedUDPPorts = let
        ports =
          mapAttrsToList (
            _: server:
              optional (server.openFirewall && server.port != null) server.port
              ++ optional (server.openFirewall && server.port6 != null) server.port6
          )
          enabledServers;
      in
        unique (flatten ports);
    })
  ];
}
