#pragma once

enum quakeReward_t
{
	QR_NONE,
	QR_FIRST_BLOOD,
	QR_HUMILIATION,
	QR_TEAM_KILL,
	QR_SUICIDE,
	QR_MULTI_KILL_2,
	QR_MULTI_KILL_3,
	QR_MULTI_KILL_4,
	QR_MULTI_KILL_5,
	QR_MULTI_KILL_6,
	QR_MULTI_KILL_7,
	QR_MULTI_KILL_8,
	QR_MULTI_KILL_9_OR_MORE,
	QR_KILLSTREAK_5,
	QR_KILLSTREAK_10,
	QR_KILLSTREAK_15,
	QR_KILLSTREAK_20,
	QR_KILLSTREAK_25,
	QR_SHUTDOWN,
	QR_NUM_REWARDS
};
